{% set name = "pysqlite" %}
{% set version = "2.8.3" %}
{% set sha256 = "17d3335863e8cf8392eea71add33dab3f96d060666fe68ab7382469d307f4490" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url:  https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

extra:
  sources:
    - sqlite-meta.yaml
  recipe-maintainers:
    - mathieu1

#build:
#  number: 0
#  script: python setup.py install
#  script: python setup.py build_static install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - pysqlite2
    - pysqlite2.test

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/ghaering/pysqlite
  license: zlib/libpng License
  summary: 'DB-API 2.0 interface for SQLite 3.x'
  license_family: OTHER